export const NFT_EARLY_ACCESS_ADDRESS = process.env.REACT_APP_NFT_EARLY_ACCESS_ADDRESS;
export const NFT_WINNER_ADDRESS = process.env.REACT_APP_NFT_WINNER_ADDRESS;
export const PUMPFUN_TOKEN_ADDRESS = process.env.REACT_APP_PUMPFUN_TOKEN_ADDRESS;
